// This file was auto generated, changes will be overwritten
// Created on Sun Apr 12 2020 23:01:37 GMT-0400 (Eastern Daylight Time)
// This module excludes Node.js specific methods so it can be used in the browser
/** @module bcijs */
export * from './compat/averageBandPowers';
export * from './compat/csp';
export * from './compat/f1score';
export * from './compat/lda';
export * from './compat/psd';
export * from './compat/psdBandPower';
export * from './compat/signal';
export * from './compat/signalBandPower';
export * from './data/partition';
export * from './data/round';
export * from './data/subscript';
export * from './data/toFixed';
export * from './data/toTable';
export * from './data/windowApply';
export * from './math/bandpower';
export * from './math/cspLearn';
export * from './math/cspProject';
export * from './math/dpss';
export * from './math/fastICA';
export * from './math/features';
export * from './math/generateSignal';
export * from './math/ldaClassify';
export * from './math/ldaLearn';
export * from './math/ldaProject';
export * from './math/multitaper';
export * from './math/nextpow2';
export * from './math/periodogram';
export * from './math/transpose';
export * from './metrics/accuracy';
export * from './metrics/balancedAccuracy';
export * from './metrics/confusionMatrix';
export * from './metrics/f1';
export * from './metrics/mcc';
export * from './metrics/precision';
export * from './metrics/recall';
export * from './metrics/specificity';
export * from './network/wait';
